version: '3'

tasks:
  # Генерация
  gen:
    cmds:
      - mkdir -p pkg/api
      - protoc -I api --go_out=pkg/api --go-grpc_out=pkg/api api/murouse/rate_limiter/v1/rate_limiter.proto

  # Линтинг
  lint:
    cmds:
      - PATH={{.LOCAL_BIN}}:{{.PATH}} golangci-lint run --config=.golangci.yml

  # Линтинг с исправлениями
  lint:fix:
    cmds:
      - PATH={{.LOCAL_BIN}}:{{.PATH}} golangci-lint run --fix --config=.golangci.yml

  # Запуск юнит-тестов
  test:
    cmds:
      - go test ./...