// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: rate_limiter.proto

package rate_limiter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Window        *durationpb.Duration   `protobuf:"bytes,3,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimitRule) Reset() {
	*x = RateLimitRule{}
	mi := &file_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimitRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitRule) ProtoMessage() {}

func (x *RateLimitRule) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitRule.ProtoReflect.Descriptor instead.
func (*RateLimitRule) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimitRule) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimitRule) GetWindow() *durationpb.Duration {
	if x != nil {
		return x.Window
	}
	return nil
}

var file_rate_limiter_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]*RateLimitRule)(nil),
		Field:         51234,
		Name:          "rate_limiter.rate_limits",
		Tag:           "bytes,51234,rep,name=rate_limits",
		Filename:      "rate_limiter.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// repeated rate_limiter.RateLimitRule rate_limits = 51234;
	E_RateLimits = &file_rate_limiter_proto_extTypes[0]
)

var File_rate_limiter_proto protoreflect.FileDescriptor

const file_rate_limiter_proto_rawDesc = "" +
	"\n" +
	"\x12rate_limiter.proto\x12\frate_limiter\x1a google/protobuf/descriptor.proto\x1a\x1egoogle/protobuf/duration.proto\"l\n" +
	"\rRateLimitRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x121\n" +
	"\x06window\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x06window:^\n" +
	"\vrate_limits\x12\x1e.google.protobuf.MethodOptions\x18\xa2\x90\x03 \x03(\v2\x1b.rate_limiter.RateLimitRuleR\n" +
	"rateLimitsB.Z,gitlab.com/murouse/rate-limiter;rate_limiterb\x06proto3"

var (
	file_rate_limiter_proto_rawDescOnce sync.Once
	file_rate_limiter_proto_rawDescData []byte
)

func file_rate_limiter_proto_rawDescGZIP() []byte {
	file_rate_limiter_proto_rawDescOnce.Do(func() {
		file_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_limiter_proto_rawDesc), len(file_rate_limiter_proto_rawDesc)))
	})
	return file_rate_limiter_proto_rawDescData
}

var file_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rate_limiter_proto_goTypes = []any{
	(*RateLimitRule)(nil),              // 0: rate_limiter.RateLimitRule
	(*durationpb.Duration)(nil),        // 1: google.protobuf.Duration
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_rate_limiter_proto_depIdxs = []int32{
	1, // 0: rate_limiter.RateLimitRule.window:type_name -> google.protobuf.Duration
	2, // 1: rate_limiter.rate_limits:extendee -> google.protobuf.MethodOptions
	0, // 2: rate_limiter.rate_limits:type_name -> rate_limiter.RateLimitRule
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	2, // [2:3] is the sub-list for extension type_name
	1, // [1:2] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rate_limiter_proto_init() }
func file_rate_limiter_proto_init() {
	if File_rate_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_limiter_proto_rawDesc), len(file_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_rate_limiter_proto_goTypes,
		DependencyIndexes: file_rate_limiter_proto_depIdxs,
		MessageInfos:      file_rate_limiter_proto_msgTypes,
		ExtensionInfos:    file_rate_limiter_proto_extTypes,
	}.Build()
	File_rate_limiter_proto = out.File
	file_rate_limiter_proto_goTypes = nil
	file_rate_limiter_proto_depIdxs = nil
}
